apiVersion: v1
kind: Pod
metadata:
  name: voting-application-pod
  labels:
    name: voting-application-pod
    app: voting-application

spec:
  containers:
    - name: voting-application
      image: dockersamples/examplevotingapp_vote
      ports:
       - containerPort: 80